#pragma once

#include <stddef.h>
#include <stdint.h>

#ifndef __has_builtin
    #define __has_builtin(...) 0
#endif

#if defined(__GNUC__) || defined(__clang__) || defined(SL_HAS_BUILTIN_EXPECT)
    #define __sl_expect(x, expected_value) __builtin_expect((x), (expected_value))
#else
    #define __sl_expect(x, expected_value) (x)
#endif

#define __sl_unlikely(x) (__sl_expect(!!(x), 0))

#if __STDC_VERSION__ >= 202000L
    // _Noreturn deprecated in C23, replaced by [[noreturn]]
    #define __sl_noreturn [[noreturn]]
#else
    #define __sl_noreturn _Noreturn
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////
// types

typedef uint8_t   __sl_u8;
typedef uint16_t  __sl_u16;
typedef uint32_t  __sl_u32;
typedef uint64_t  __sl_u64;
typedef int8_t    __sl_i8;
typedef int16_t   __sl_i16;
typedef int32_t   __sl_i32;
typedef int64_t   __sl_i64;
typedef size_t    __sl_uint;
typedef ptrdiff_t __sl_int;
typedef float     __sl_f32;
typedef double    __sl_f64;
typedef _Bool     __sl_bool;
typedef __sl_u64  __sl_type;

typedef struct {
    const void* ptr;
    __sl_int    len;
} __sl_slice_ro;

typedef struct {
    void*    ptr;
    __sl_int len;
} __sl_slice_mut;

// BEGIN generated code
/* Code generated by tools/gen_builtin_abi.py from lib/builtin/*.sl and lib/platform/platform.sl. DO
 * NOT EDIT. */

typedef struct __sl_str          __sl_str;
typedef struct __sl_Logger       __sl_Logger;
typedef struct __sl_Allocator    __sl_Allocator;
typedef struct __sl_Context      __sl_Context;
typedef struct __sl_PrintContext __sl_PrintContext;

struct __sl_str {
    __sl_u8* ptr;
    __sl_int len;
};

typedef __sl_u32 __sl_rune;

typedef enum {
    __sl_LogLevel_Trace = -20,
    __sl_LogLevel_Debug = -10,
    __sl_LogLevel_Info = 0,
    __sl_LogLevel_Warning = 20,
    __sl_LogLevel_Error = 30,
    __sl_LogLevel_Fatal = 40,
} __sl_LogLevel;

typedef enum {
    __sl_LogFlag_Level = 1 << 0,
    __sl_LogFlag_Date = 1 << 1,
    __sl_LogFlag_Time = 1 << 2,
    __sl_LogFlag_ShortFile = 1 << 3,
    __sl_LogFlag_LongFile = 1 << 4,
    __sl_LogFlag_Line = 1 << 5,
    __sl_LogFlag_Function = 1 << 6,
    __sl_LogFlag_Thread = 1 << 7,
    __sl_LogFlag_Styling = 1 << 8,
    __sl_LogFlag_Prefix = 1 << 9,
} __sl_LogFlag;

typedef __sl_u32 __sl_LogFlags;

struct __sl_Logger {
    void (*handler)(__sl_Logger* arg0, __sl_str arg1, __sl_LogLevel arg2, __sl_LogFlags arg3);
    __sl_LogLevel min_level;
    __sl_LogFlags flags;
    __sl_str      prefix;
};

struct __sl_Allocator {
    void* (*impl)(
        __sl_Allocator* arg0,
        void*           arg1,
        __sl_int        arg2,
        __sl_int        arg3,
        __sl_int*       arg4,
        __sl_u32        arg5);
};

struct __sl_Context {
    __sl_Allocator* mem;
    __sl_Allocator* temp_mem;
    __sl_Logger     log;
};

struct __sl_PrintContext {
    __sl_Logger log;
};
// END generated code

////////////////////////////////////////////////////////////////////////////////////////////////////
// functions

__sl_noreturn void __sl_panic(const __sl_str* msg, const char* file, __sl_u32 line);
#define __sl_strlit(strlit)                                \
    (&(const __sl_str){                                    \
        .ptr = (__sl_u8*)(uintptr_t)(const void*)(strlit), \
        .len = (__sl_int)(sizeof(strlit) - 1u) })
#define __sl_strlitp(strlit) __sl_strlit(strlit)

#define __sl_assert(expr)                                                     \
    do {                                                                      \
        if __sl_unlikely (!(expr)) {                                          \
            __sl_panic(__sl_strlitp("assertion failed"), __FILE__, __LINE__); \
        }                                                                     \
    } while (0)

#define __sl_assertf(expr, fmt_cstr_lit, ...)                           \
    do {                                                                \
        if __sl_unlikely (!(expr)) {                                    \
            __sl_panic(__sl_strlitp(fmt_cstr_lit), __FILE__, __LINE__); \
        }                                                               \
    } while (0)

static inline __sl_int __sl_len(__sl_str s) {
    return s.len;
}

static inline const __sl_u8* __sl_cstr(__sl_str s) {
    return s.ptr;
}

static inline __sl_int __sl_align_up(__sl_int x, __sl_int a) {
    if __sl_unlikely (x < 0 || a <= 0 || (a & (a - 1)) != 0) {
        __sl_panic(__sl_strlitp("invalid size or alignment"), "", 0);
    }
    return (x + (a - 1)) & ~(a - 1);
}

static inline __sl_uint __sl_checked_uint_size(__sl_int n) {
    if __sl_unlikely (n < 0) {
        __sl_panic(__sl_strlitp("negative size"), "", 0);
    }
    return (__sl_uint)n;
}

static inline __sl_int __sl_packed_str_size(const __sl_str* s) {
    if __sl_unlikely (s == NULL || s->len < 0) {
        __sl_panic(__sl_strlitp("invalid string length"), "", 0);
    }
    return (__sl_int)sizeof(__sl_str) + s->len + 1;
}

int  __sl_memcmp(const void* a, const void* b, __sl_uint n);
void __sl_memcpy(void* dst, const void* src, __sl_uint n);
void __sl_memmove(void* dst, const void* src, __sl_uint n);

// use compiler intrinsics when available
#if __has_builtin(__builtin_memcpy)
    #define __sl_memcpy __builtin_memcpy
#endif
#if __has_builtin(__builtin_memmove)
    #define __sl_memmove __builtin_memmove
#endif
#if __has_builtin(__builtin_memcmp)
    #define __sl_memcmp __builtin_memcmp
#endif
// #define memset  __builtin_memset
// #define memset  __builtin_memset_inline

__sl_int __sl_copy(
    void* dst, __sl_int dst_len, const void* src, __sl_int src_len, __sl_int elem_size);

static inline __sl_bool __sl_mem_equal(const void* a, const void* b, __sl_uint n) {
    return n == 0u || __sl_memcmp(a, b, n) == 0;
}

__sl_int __sl_mem_order(const void* a, __sl_int a_len, const void* b, __sl_int b_len);

static inline __sl_bool __sl_str_equal(__sl_str a, __sl_str b) {
    __sl_int a_len = __sl_len(a);
    __sl_int b_len = __sl_len(b);
    return a_len == b_len
        && __sl_mem_equal(
               (const void*)__sl_cstr(a), (const void*)__sl_cstr(b), __sl_checked_uint_size(a_len));
}

static inline __sl_int __sl_str_order(__sl_str a, __sl_str b) {
    return __sl_mem_order(
        (const void*)__sl_cstr(a), __sl_len(a), (const void*)__sl_cstr(b), __sl_len(b));
}

static inline __sl_bool __sl_slice_equal_ro(__sl_slice_ro a, __sl_slice_ro b, __sl_int elem_size) {
    __sl_uint a_bytes = __sl_checked_uint_size(a.len * elem_size);
    __sl_uint b_bytes = __sl_checked_uint_size(b.len * elem_size);
    return a.len == b.len && __sl_mem_equal(a.ptr, b.ptr, a_bytes < b_bytes ? a_bytes : b_bytes);
}

static inline __sl_int __sl_slice_order_ro(__sl_slice_ro a, __sl_slice_ro b, __sl_int elem_size) {
    return __sl_mem_order(a.ptr, a.len * elem_size, b.ptr, b.len * elem_size);
}

static inline __sl_int __sl_ptr_order(const void* a, const void* b) {
    uintptr_t aa = (uintptr_t)a;
    uintptr_t bb = (uintptr_t)b;
    if (aa < bb) {
        return -1;
    }
    if (aa > bb) {
        return 1;
    }
    return 0;
}

static inline void* __sl_unwrap1(const char* file, __sl_u32 line, const void* p) {
    if __sl_unlikely (p == NULL) {
        __sl_panic(__sl_strlitp("unwrap: null value"), file, line);
    }
    return (void*)p;
}

#define __sl_unwrap(p) __sl_unwrap1(__FILE__, __LINE__, (p))

static inline void* __sl_new(__sl_Allocator* ma, __sl_int size, __sl_int align) {
    __sl_int newSize = size;

    if __sl_unlikely (size < 0 || align <= 0 || (align & (align - 1)) != 0) {
        __sl_panic(__sl_strlitp("invalid alignment"), "", 0);
    }

    if __sl_unlikely (ma == NULL || ma->impl == NULL) {
        __sl_panic(__sl_strlitp("invalid allocator"), "", 0);
    }

    return ma->impl(ma, NULL, align, 0, &newSize, 0);
}

static inline void __sl_free(__sl_Allocator* ma, void* p, __sl_int curSize, __sl_int align) {
    __sl_int newSize = 0;
    if (p == NULL || ma == NULL || ma->impl == NULL) {
        return;
    }
    (void)ma->impl(ma, p, align, curSize, &newSize, 0);
}

static inline void* __sl_new_array(
    __sl_Allocator* ma, __sl_int elemSize, __sl_int elemAlign, __sl_int count) {
    if __sl_unlikely (elemSize < 0 || count < 0) {
        __sl_panic(__sl_strlitp("negative size"), "", 0);
    }
    return __sl_new(ma, elemSize * count, elemAlign);
}

static inline __sl_slice_ro __sl_new_array_slice_ro(
    __sl_Allocator* ma, __sl_int elemSize, __sl_int elemAlign, __sl_int count) {
    void* p = __sl_new_array(ma, elemSize, elemAlign, count);
    return (__sl_slice_ro){ .ptr = p, .len = p != NULL ? count : 0 };
}

static inline __sl_slice_mut __sl_new_array_slice_mut(
    __sl_Allocator* ma, __sl_int elemSize, __sl_int elemAlign, __sl_int count) {
    void* p = __sl_new_array(ma, elemSize, elemAlign, count);
    return (__sl_slice_mut){ .ptr = p, .len = p != NULL ? count : 0 };
}
