#pragma once

#include <stddef.h>
#include <stdint.h>

#ifndef __has_builtin
    #define __has_builtin(...) 0
#endif

#if defined(__GNUC__) || defined(__clang__) || defined(HOP_HAS_BUILTIN_EXPECT)
    #define __hop_expect(x, expected_value) __builtin_expect((x), (expected_value))
#else
    #define __hop_expect(x, expected_value) (x)
#endif

#define __hop_unlikely(x) (__hop_expect(!!(x), 0))

#if __STDC_VERSION__ >= 202000L
    // _Noreturn deprecated in C23, replaced by [[noreturn]]
    #define __hop_noreturn [[noreturn]]
#else
    #define __hop_noreturn _Noreturn
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////
// types

typedef uint8_t   __hop_u8;
typedef uint16_t  __hop_u16;
typedef uint32_t  __hop_u32;
typedef uint64_t  __hop_u64;
typedef int8_t    __hop_i8;
typedef int16_t   __hop_i16;
typedef int32_t   __hop_i32;
typedef int64_t   __hop_i64;
typedef size_t    __hop_uint;
typedef ptrdiff_t __hop_int;
typedef float     __hop_f32;
typedef double    __hop_f64;
typedef _Bool     __hop_bool;
typedef __hop_u64 __hop_type;

typedef struct {
    const void* ptr;
    __hop_int   len;
} __hop_slice_ro;

typedef struct {
    void*     ptr;
    __hop_int len;
} __hop_slice_mut;

// BEGIN generated code
/* Code generated by tools/gen_builtin_abi.py from lib/builtin/*.hop and lib/platform/platform.hop.
 * DO NOT EDIT. */

typedef struct __hop_str            __hop_str;
typedef struct __hop_SourceLocation __hop_SourceLocation;
typedef struct __hop_Logger         __hop_Logger;
typedef struct __hop_MemAllocator   __hop_MemAllocator;
typedef struct __hop_Context        __hop_Context;
typedef struct __hop_PrintContext   __hop_PrintContext;

struct __hop_str {
    __hop_u8* ptr;
    __hop_int len;
};

typedef __hop_u32 __hop_rune;

typedef enum {
    __hop_LogLevel_Trace = -20,
    __hop_LogLevel_Debug = -10,
    __hop_LogLevel_Info = 0,
    __hop_LogLevel_Warning = 20,
    __hop_LogLevel_Error = 30,
    __hop_LogLevel_Fatal = 40,
} __hop_LogLevel;

typedef enum {
    __hop_LogFlag_Level = 1 << 0,
    __hop_LogFlag_Date = 1 << 1,
    __hop_LogFlag_Time = 1 << 2,
    __hop_LogFlag_ShortFile = 1 << 3,
    __hop_LogFlag_LongFile = 1 << 4,
    __hop_LogFlag_Line = 1 << 5,
    __hop_LogFlag_Function = 1 << 6,
    __hop_LogFlag_Thread = 1 << 7,
    __hop_LogFlag_Styling = 1 << 8,
    __hop_LogFlag_Prefix = 1 << 9,
} __hop_LogFlag;

typedef __hop_u32 __hop_LogFlags;

struct __hop_SourceLocation {
    __hop_str file;
    __hop_int start_line;
    __hop_int start_column;
    __hop_int end_line;
    __hop_int end_column;
};

struct __hop_Logger {
    void (*handler)(__hop_Logger* arg0, __hop_str arg1, __hop_LogLevel arg2, __hop_LogFlags arg3);
    __hop_LogLevel min_level;
    __hop_LogFlags flags;
    __hop_str      prefix;
};

struct __hop_MemAllocator {
    void* (*handler)(
        __hop_MemAllocator*  arg0,
        void*                arg1,
        __hop_int            arg2,
        __hop_int            arg3,
        __hop_int*           arg4,
        __hop_u32            arg5,
        __hop_SourceLocation arg6);
};

struct __hop_Context {
    __hop_MemAllocator allocator;
    __hop_MemAllocator temp_allocator;
    __hop_Logger       logger;
    void*              user1;
    void*              user2;
    void*              _reserved;
    __hop_u64          deadline;
};

struct __hop_PrintContext {
    __hop_Logger logger;
};
// END generated code

////////////////////////////////////////////////////////////////////////////////////////////////////
// functions

__hop_noreturn void __hop_panic(const __hop_str* msg, const char* file, __hop_u32 line);
#define __hop_strlit(strlit)                                \
    (&(const __hop_str){                                    \
        .ptr = (__hop_u8*)(uintptr_t)(const void*)(strlit), \
        .len = (__hop_int)(sizeof(strlit) - 1u) })
#define __hop_strlitp(strlit) __hop_strlit(strlit)

#define __hop_assert(expr)                                                      \
    do {                                                                        \
        if __hop_unlikely (!(expr)) {                                           \
            __hop_panic(__hop_strlitp("assertion failed"), __FILE__, __LINE__); \
        }                                                                       \
    } while (0)

#define __hop_assertf(expr, fmt_cstr_lit, ...)                            \
    do {                                                                  \
        if __hop_unlikely (!(expr)) {                                     \
            __hop_panic(__hop_strlitp(fmt_cstr_lit), __FILE__, __LINE__); \
        }                                                                 \
    } while (0)

static inline __hop_int __hop_len(__hop_str s) {
    return s.len;
}

static inline const __hop_u8* __hop_cstr(__hop_str s) {
    return s.ptr;
}

static inline __hop_int __hop_align_up(__hop_int x, __hop_int a) {
    if __hop_unlikely (x < 0 || a <= 0 || (a & (a - 1)) != 0) {
        __hop_panic(__hop_strlitp("invalid size or alignment"), "", 0);
    }
    return (x + (a - 1)) & ~(a - 1);
}

static inline __hop_uint __hop_checked_uint_size(__hop_int n) {
    if __hop_unlikely (n < 0) {
        __hop_panic(__hop_strlitp("negative size"), "", 0);
    }
    return (__hop_uint)n;
}

static inline __hop_int __hop_packed_str_size(const __hop_str* s) {
    if __hop_unlikely (s == NULL || s->len < 0) {
        __hop_panic(__hop_strlitp("invalid string length"), "", 0);
    }
    return (__hop_int)sizeof(__hop_str) + s->len + 1;
}

int  __hop_memcmp(const void* a, const void* b, __hop_uint n);
void __hop_memcpy(void* dst, const void* src, __hop_uint n);
void __hop_memmove(void* dst, const void* src, __hop_uint n);

// use compiler intrinsics when available
#if __has_builtin(__builtin_memcpy)
    #define __hop_memcpy __builtin_memcpy
#endif
#if __has_builtin(__builtin_memmove)
    #define __hop_memmove __builtin_memmove
#endif
#if __has_builtin(__builtin_memcmp)
    #define __hop_memcmp __builtin_memcmp
#endif
// #define memset  __builtin_memset
// #define memset  __builtin_memset_inline

__hop_int __hop_copy(
    void* dst, __hop_int dst_len, const void* src, __hop_int src_len, __hop_int elem_size);

static inline __hop_bool __hop_mem_equal(const void* a, const void* b, __hop_uint n) {
    return n == 0u || __hop_memcmp(a, b, n) == 0;
}

__hop_int __hop_mem_order(const void* a, __hop_int a_len, const void* b, __hop_int b_len);

static inline __hop_bool __hop_str_equal(__hop_str a, __hop_str b) {
    __hop_int a_len = __hop_len(a);
    __hop_int b_len = __hop_len(b);
    return a_len == b_len
        && __hop_mem_equal(
               (const void*)__hop_cstr(a),
               (const void*)__hop_cstr(b),
               __hop_checked_uint_size(a_len));
}

static inline __hop_int __hop_str_order(__hop_str a, __hop_str b) {
    return __hop_mem_order(
        (const void*)__hop_cstr(a), __hop_len(a), (const void*)__hop_cstr(b), __hop_len(b));
}

static inline __hop_bool __hop_slice_equal_ro(
    __hop_slice_ro a, __hop_slice_ro b, __hop_int elem_size) {
    __hop_uint a_bytes = __hop_checked_uint_size(a.len * elem_size);
    __hop_uint b_bytes = __hop_checked_uint_size(b.len * elem_size);
    return a.len == b.len && __hop_mem_equal(a.ptr, b.ptr, a_bytes < b_bytes ? a_bytes : b_bytes);
}

static inline __hop_int __hop_slice_order_ro(
    __hop_slice_ro a, __hop_slice_ro b, __hop_int elem_size) {
    return __hop_mem_order(a.ptr, a.len * elem_size, b.ptr, b.len * elem_size);
}

static inline __hop_int __hop_ptr_order(const void* a, const void* b) {
    uintptr_t aa = (uintptr_t)a;
    uintptr_t bb = (uintptr_t)b;
    if (aa < bb) {
        return -1;
    }
    if (aa > bb) {
        return 1;
    }
    return 0;
}

static inline void* __hop_unwrap1(const char* file, __hop_u32 line, const void* p) {
    if __hop_unlikely (p == NULL) {
        __hop_panic(__hop_strlitp("unwrap: null value"), file, line);
    }
    return (void*)p;
}

#define __hop_unwrap(p) __hop_unwrap1(__FILE__, __LINE__, (p))

static inline __hop_SourceLocation __hop_source_location(const char* file, __hop_u32 line) {
    (void)file;
    (void)line;
    return (__hop_SourceLocation){ 0 };
}

static inline void* __hop_new(__hop_MemAllocator* ma, __hop_int size, __hop_int align) {
    __hop_int newSize = size;

    if __hop_unlikely (size < 0 || align <= 0 || (align & (align - 1)) != 0) {
        __hop_panic(__hop_strlitp("invalid alignment"), "", 0);
    }

    if __hop_unlikely (ma == NULL || ma->handler == NULL) {
        __hop_panic(__hop_strlitp("invalid allocator"), "", 0);
    }

    return ma->handler(ma, NULL, align, 0, &newSize, 0, __hop_source_location(__FILE__, __LINE__));
}

static inline void __hop_free(__hop_MemAllocator* ma, void* p, __hop_int curSize, __hop_int align) {
    __hop_int newSize = 0;
    if (p == NULL || ma == NULL || ma->handler == NULL) {
        return;
    }
    (void)ma->handler(
        ma, p, align, curSize, &newSize, 0, __hop_source_location(__FILE__, __LINE__));
}

static inline void* __hop_new_array(
    __hop_MemAllocator* ma, __hop_int elemSize, __hop_int elemAlign, __hop_int count) {
    if __hop_unlikely (elemSize < 0 || count < 0) {
        __hop_panic(__hop_strlitp("negative size"), "", 0);
    }
    return __hop_new(ma, elemSize * count, elemAlign);
}

static inline __hop_slice_ro __hop_new_array_slice_ro(
    __hop_MemAllocator* ma, __hop_int elemSize, __hop_int elemAlign, __hop_int count) {
    void* p = __hop_new_array(ma, elemSize, elemAlign, count);
    return (__hop_slice_ro){ .ptr = p, .len = p != NULL ? count : 0 };
}

static inline __hop_slice_mut __hop_new_array_slice_mut(
    __hop_MemAllocator* ma, __hop_int elemSize, __hop_int elemAlign, __hop_int count) {
    void* p = __hop_new_array(ma, elemSize, elemAlign, count);
    return (__hop_slice_mut){ .ptr = p, .len = p != NULL ? count : 0 };
}
