#pragma once

#include <stddef.h>
#include <stdint.h>

#ifndef __has_builtin
    #define __has_builtin(...) 0
#endif

#if defined(__GNUC__) || defined(__clang__) || defined(SL_HAS_BUILTIN_EXPECT)
    #define __sl_expect(x, expected_value) __builtin_expect((x), (expected_value))
#else
    #define __sl_expect(x, expected_value) (x)
#endif

#define __sl_unlikely(x) (__sl_expect(!!(x), 0))

#if __STDC_VERSION__ >= 202000L
    // _Noreturn deprecated in C23, replaced by [[noreturn]]
    #define __sl_noreturn [[noreturn]]
#else
    #define __sl_noreturn _Noreturn
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////
// types

typedef uint8_t   __sl_u8;
typedef uint16_t  __sl_u16;
typedef uint32_t  __sl_u32;
typedef uint64_t  __sl_u64;
typedef int8_t    __sl_i8;
typedef int16_t   __sl_i16;
typedef int32_t   __sl_i32;
typedef int64_t   __sl_i64;
typedef size_t    __sl_uint;
typedef ptrdiff_t __sl_int;
typedef float     __sl_f32;
typedef double    __sl_f64;
typedef _Bool     __sl_bool;
typedef __sl_u64  __sl_type;

typedef struct {
    const void* ptr;
    __sl_uint   len;
} __sl_slice_ro;

typedef struct {
    void*     ptr;
    __sl_uint len;
} __sl_slice_mut;

// BEGIN generated code
/* Code generated by tools/gen_builtin_abi.py from lib/builtin/*.sl and lib/platform/platform.sl. DO
 * NOT EDIT. */

typedef struct __sl_str          __sl_str;
typedef struct __sl_Logger       __sl_Logger;
typedef struct __sl_Allocator    __sl_Allocator;
typedef struct __sl_Context      __sl_Context;
typedef struct __sl_PrintContext __sl_PrintContext;

struct __sl_str {
    __sl_u8*  ptr;
    __sl_uint len;
};

typedef __sl_u32 __sl_rune;

typedef enum {
    __sl_LogLevel_Trace = -20,
    __sl_LogLevel_Debug = -10,
    __sl_LogLevel_Info = 0,
    __sl_LogLevel_Warning = 20,
    __sl_LogLevel_Error = 30,
    __sl_LogLevel_Fatal = 40,
} __sl_LogLevel;

typedef enum {
    __sl_LogFlag_Level = 1 << 0,
    __sl_LogFlag_Date = 1 << 1,
    __sl_LogFlag_Time = 1 << 2,
    __sl_LogFlag_ShortFile = 1 << 3,
    __sl_LogFlag_LongFile = 1 << 4,
    __sl_LogFlag_Line = 1 << 5,
    __sl_LogFlag_Function = 1 << 6,
    __sl_LogFlag_Thread = 1 << 7,
    __sl_LogFlag_Styling = 1 << 8,
    __sl_LogFlag_Prefix = 1 << 9,
} __sl_LogFlag;

typedef __sl_u32 __sl_LogFlags;

struct __sl_Logger {
    void (*handler)(__sl_Logger* arg0, __sl_str* arg1, __sl_LogLevel arg2, __sl_LogFlags arg3);
    __sl_LogLevel min_level;
    __sl_LogFlags flags;
    __sl_str*     prefix;
};

struct __sl_Allocator {
    __sl_uint (*impl)(
        __sl_Allocator* arg0,
        __sl_uint       arg1,
        __sl_uint       arg2,
        __sl_uint       arg3,
        __sl_uint*      arg4,
        __sl_u32        arg5);
};

struct __sl_Context {
    __sl_Allocator* mem;
    __sl_Allocator* temp_mem;
    __sl_Logger     log;
};

struct __sl_PrintContext {
    __sl_Logger log;
};
// END generated code

////////////////////////////////////////////////////////////////////////////////////////////////////
// functions

__sl_noreturn void __sl_panic(const __sl_str* msg, const char* file, __sl_u32 line);
#define __sl_strlit(strlit)                                \
    (&(const __sl_str){                                    \
        .ptr = (__sl_u8*)(uintptr_t)(const void*)(strlit), \
        .len = (__sl_uint)(sizeof(strlit) - 1u) })

#define __sl_assert(expr)                                                    \
    do {                                                                     \
        if __sl_unlikely (!(expr)) {                                         \
            __sl_panic(__sl_strlit("assertion failed"), __FILE__, __LINE__); \
        }                                                                    \
    } while (0)

#define __sl_assertf(expr, fmt_cstr_lit, ...)                          \
    do {                                                               \
        if __sl_unlikely (!(expr)) {                                   \
            __sl_panic(__sl_strlit(fmt_cstr_lit), __FILE__, __LINE__); \
        }                                                              \
    } while (0)

static inline __sl_uint __sl_len(const __sl_str* s) {
    return s->len;
}

static inline const __sl_u8* __sl_cstr(const __sl_str* s) {
    return s->ptr;
}

static inline __sl_uint __sl_align_up(__sl_uint x, __sl_uint a) {
    return (x + (a - 1u)) & ~(a - 1u);
}

static inline __sl_uint __sl_str_sizeof(const __sl_str* s) {
    return (__sl_uint)(sizeof(__sl_str) + (__sl_uint)s->len + 1u);
}

int  __sl_memcmp(const void* a, const void* b, __sl_uint n);
void __sl_memcpy(void* dst, const void* src, __sl_uint n);
void __sl_memmove(void* dst, const void* src, __sl_uint n);

// use compiler intrinsics when available
#if __has_builtin(__builtin_memcpy)
    #define __sl_memcpy __builtin_memcpy
#endif
#if __has_builtin(__builtin_memmove)
    #define __sl_memmove __builtin_memmove
#endif
#if __has_builtin(__builtin_memcmp)
    #define __sl_memcmp __builtin_memcmp
#endif
// #define memset  __builtin_memset
// #define memset  __builtin_memset_inline

__sl_uint __sl_copy(
    void* dst, __sl_uint dst_len, const void* src, __sl_uint src_len, __sl_uint elem_size);

static inline __sl_bool __sl_mem_equal(const void* a, const void* b, __sl_uint n) {
    return n == 0u || __sl_memcmp(a, b, n) == 0;
}

__sl_int __sl_mem_order(const void* a, __sl_uint a_len, const void* b, __sl_uint b_len);

static inline __sl_bool __sl_str_equal(const __sl_str* a, const __sl_str* b) {
    __sl_uint a_len = __sl_len(a);
    __sl_uint b_len = __sl_len(b);
    return a_len == b_len
        && __sl_mem_equal((const void*)__sl_cstr(a), (const void*)__sl_cstr(b), a_len);
}

static inline __sl_int __sl_str_order(const __sl_str* a, const __sl_str* b) {
    return __sl_mem_order(
        (const void*)__sl_cstr(a), __sl_len(a), (const void*)__sl_cstr(b), __sl_len(b));
}

static inline __sl_bool __sl_slice_equal_ro(__sl_slice_ro a, __sl_slice_ro b, __sl_uint elem_size) {
    __sl_uint a_bytes = a.len * elem_size;
    __sl_uint b_bytes = b.len * elem_size;
    return a.len == b.len && __sl_mem_equal(a.ptr, b.ptr, a_bytes < b_bytes ? a_bytes : b_bytes);
}

static inline __sl_int __sl_slice_order_ro(__sl_slice_ro a, __sl_slice_ro b, __sl_uint elem_size) {
    return __sl_mem_order(a.ptr, a.len * elem_size, b.ptr, b.len * elem_size);
}

static inline __sl_int __sl_ptr_order(const void* a, const void* b) {
    uintptr_t aa = (uintptr_t)a;
    uintptr_t bb = (uintptr_t)b;
    if (aa < bb) {
        return -1;
    }
    if (aa > bb) {
        return 1;
    }
    return 0;
}

static inline void* __sl_unwrap1(const char* file, __sl_u32 line, const void* p) {
    if __sl_unlikely (p == NULL) {
        __sl_panic(__sl_strlit("unwrap: null value"), file, line);
    }
    return (void*)p;
}

#define __sl_unwrap(p) __sl_unwrap1(__FILE__, __LINE__, (p))

static inline void* __sl_new(__sl_Allocator* ma, __sl_uint size, __sl_uint align) {
    __sl_uint newSize = size;

    if __sl_unlikely (align == 0 || (align & (align - 1u)) != 0) {
        __sl_panic(__sl_strlit("invalid alignment"), "", 0);
    }

    // TODO FIXME: make ma or ma->impl being NULL an error. For now we return NULL in that case,
    // as if allocation failed, since several tests makes this assumption.
    if __sl_unlikely (ma == NULL || ma->impl == NULL) {
        // __sl_panic(__sl_strlit("ma.impl is null"), "", 0);
        return NULL;
    }

    return (void*)(uintptr_t)ma->impl(ma, 0, align, 0, &newSize, 0);
}

static inline void __sl_free(__sl_Allocator* ma, void* p, __sl_uint curSize, __sl_uint align) {
    __sl_uint newSize = 0;
    if (p == NULL || ma == NULL || ma->impl == NULL) {
        return;
    }
    (void)ma->impl(ma, (__sl_uint)(uintptr_t)p, align, curSize, &newSize, 0);
}

static inline void* __sl_new_array(
    __sl_Allocator* ma, __sl_uint elemSize, __sl_uint elemAlign, __sl_uint count) {
    return __sl_new(ma, elemSize * count, elemAlign);
}

static inline __sl_slice_ro __sl_new_array_slice_ro(
    __sl_Allocator* ma, __sl_uint elemSize, __sl_uint elemAlign, __sl_uint count) {
    void* p = __sl_new_array(ma, elemSize, elemAlign, count);
    return (__sl_slice_ro){ .ptr = p, .len = p != NULL ? count : 0u };
}

static inline __sl_slice_mut __sl_new_array_slice_mut(
    __sl_Allocator* ma, __sl_uint elemSize, __sl_uint elemAlign, __sl_uint count) {
    void* p = __sl_new_array(ma, elemSize, elemAlign, count);
    return (__sl_slice_mut){ .ptr = p, .len = p != NULL ? count : 0u };
}
