#!/usr/bin/env python3
import argparse
import json
import re
import sys
from pathlib import Path


def fail(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    raise SystemExit(1)


def c_escape(s: str) -> str:
    return (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def sanitize_name(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9_]", "_", name)
    s = re.sub(r"_+", "_", s)
    if s == "":
        s = "_"
    if s[0].isdigit():
        s = "_" + s
    return s


def to_printf_fmt(message: str) -> tuple[str, int]:
    out: list[str] = []
    i = 0
    arg_count = 0
    while i < len(message):
        if message.startswith("{s}", i):
            out.append("%s")
            arg_count += 1
            i += 3
            continue
        if message[i] == "%":
            out.append("%%")
        else:
            out.append(message[i])
        i += 1
    return ("".join(out), arg_count)


def load_entries(path: Path) -> list[dict[str, str | int]]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        fail(f"{path}: invalid JSON: {e}")

    if not isinstance(data, dict):
        fail(f"{path}: top-level JSON value must be an object")

    id_re = re.compile(r"^SL([1-9][0-9]*)$")
    seen_enum: set[str] = set()
    entries: list[dict[str, str | int]] = []

    for diag_id, v in data.items():
        if not isinstance(diag_id, str) or id_re.match(diag_id) is None:
            fail(f"{path}: invalid diagnostic key '{diag_id}', expected SL<positive-int>")
        if not isinstance(v, dict):
            fail(f"{path}:{diag_id}: expected object")
        message = v.get("message")
        if not isinstance(message, str) or message == "":
            fail(f"{path}:{diag_id}: 'message' must be a non-empty string")
        name = v.get("name")
        if name is None:
            enum_suffix = "_" + diag_id
        else:
            if not isinstance(name, str) or name == "":
                fail(f"{path}:{diag_id}: 'name' must be a non-empty string when provided")
            enum_suffix = sanitize_name(name)
        enum_name = "SLDiag_" + enum_suffix
        if enum_name in seen_enum:
            fail(f"{path}:{diag_id}: duplicate enum name '{enum_name}'")
        seen_enum.add(enum_name)

        diag_type = v.get("type", "error")
        if not isinstance(diag_type, str):
            fail(f"{path}:{diag_id}: 'type' must be a string when provided")
        if diag_type not in ("error", "warning"):
            fail(f"{path}:{diag_id}: 'type' must be 'error' or 'warning'")

        hint = v.get("hint", "")
        if hint is None:
            hint = ""
        if not isinstance(hint, str):
            fail(f"{path}:{diag_id}: 'hint' must be a string when provided")

        printf_fmt, arg_count = to_printf_fmt(message)
        if arg_count > 1:
            fail(f"{path}:{diag_id}: currently supports at most one '{{s}}' placeholder")

        entries.append(
            {
                "id": diag_id,
                "enum": enum_name,
                "message": message,
                "fmt": printf_fmt,
                "hint": hint,
                "type": diag_type,
                "arg_count": arg_count,
            }
        )

    if len(entries) == 0:
        fail(f"{path}: diagnostics map must not be empty")

    return entries


def render_enum_inc(entries: list[dict[str, str | int]], rel_json: str) -> str:
    lines: list[str] = []
    lines.append("/* Code generated by tools/gen_diagnostics.py. DO NOT EDIT. */")
    lines.append(f"/* Source: {rel_json} */")
    lines.append("SLDiag_NONE = 0,")
    for e in entries:
        lines.append(f'{e["enum"]}, /* {e["id"]}: {e["message"]} */')
    lines.append("")
    return "\n".join(lines)


def render_data_c(entries: list[dict[str, str | int]], rel_json: str) -> str:
    lines: list[str] = []
    lines.append("/* Code generated by tools/gen_diagnostics.py. DO NOT EDIT. */")
    lines.append(f"/* Source: {rel_json} */")
    lines.append('#include "libsl-impl.h"')
    lines.append("")
    lines.append("SL_API_BEGIN")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    const char* id;")
    lines.append("    const char* messageFmt;")
    lines.append("    const char* hint;")
    lines.append("    SLDiagType  type;")
    lines.append("    uint8_t     argCount;")
    lines.append("} SLDiagInfo;")
    lines.append("")
    lines.append("static const SLDiagInfo g_slDiagInfo[SLDiag__COUNT] = {")
    lines.append('    [SLDiag_NONE] = { "", "no error", NULL, SLDiagType_ERROR, 0 },')
    for e in entries:
        hint = "NULL" if e["hint"] == "" else f"\"{c_escape(str(e['hint']))}\""
        diag_type = "SLDiagType_WARNING" if e["type"] == "warning" else "SLDiagType_ERROR"
        lines.append(
            f'    [{e["enum"]}] = {{ "{c_escape(str(e["id"]))}", "{c_escape(str(e["fmt"]))}",'
            f" {hint}, {diag_type}, {e['arg_count']} }},"
        )
    lines.append("};")
    lines.append("")
    lines.append("const char* SLDiagId(SLDiagCode code) {")
    lines.append("    uint32_t i = (uint32_t)code;")
    lines.append("    if (i >= (uint32_t)SLDiag__COUNT || g_slDiagInfo[i].id == NULL) {")
    lines.append('        return "SL????";')
    lines.append("    }")
    lines.append("    return g_slDiagInfo[i].id;")
    lines.append("}")
    lines.append("")
    lines.append("const char* SLDiagMessage(SLDiagCode code) {")
    lines.append("    uint32_t i = (uint32_t)code;")
    lines.append("    if (i >= (uint32_t)SLDiag__COUNT || g_slDiagInfo[i].messageFmt == NULL) {")
    lines.append('        return "unknown diagnostic";')
    lines.append("    }")
    lines.append("    return g_slDiagInfo[i].messageFmt;")
    lines.append("}")
    lines.append("")
    lines.append("const char* _Nullable SLDiagHint(SLDiagCode code) {")
    lines.append("    uint32_t i = (uint32_t)code;")
    lines.append("    if (i >= (uint32_t)SLDiag__COUNT) {")
    lines.append("        return NULL;")
    lines.append("    }")
    lines.append("    return g_slDiagInfo[i].hint;")
    lines.append("}")
    lines.append("")
    lines.append("SLDiagType SLDiagTypeOfCode(SLDiagCode code) {")
    lines.append("    uint32_t i = (uint32_t)code;")
    lines.append("    if (i >= (uint32_t)SLDiag__COUNT) {")
    lines.append("        return SLDiagType_ERROR;")
    lines.append("    }")
    lines.append("    return g_slDiagInfo[i].type;")
    lines.append("}")
    lines.append("")
    lines.append("uint8_t SLDiagArgCount(SLDiagCode code) {")
    lines.append("    uint32_t i = (uint32_t)code;")
    lines.append("    if (i >= (uint32_t)SLDiag__COUNT) {")
    lines.append("        return 0;")
    lines.append("    }")
    lines.append("    return g_slDiagInfo[i].argCount;")
    lines.append("}")
    lines.append("")
    lines.append("SL_API_END")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", required=True, type=Path)
    ap.add_argument("--enum-out", required=True, type=Path)
    ap.add_argument("--c-out", required=True, type=Path)
    args = ap.parse_args()

    entries = load_entries(args.json)
    rel_json = str(args.json).replace("\\", "/")

    write_file(args.enum_out, render_enum_inc(entries, rel_json))
    write_file(args.c_out, render_data_c(entries, rel_json))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
