/* Code generated by tools/gen_diagnostics.py. DO NOT EDIT. */
/* Source: src/diagnostics.json */
#include "libsl-impl.h"

SL_API_BEGIN

typedef struct {
    const char* id;
    const char* messageFmt;
    const char* hint;
    SLDiagType  type;
    uint8_t     argCount;
} SLDiagInfo;

static const SLDiagInfo g_slDiagInfo[SLDiag__COUNT] = {
    [SLDiag_NONE] = { "", "no error", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_ARENA_OOM] = { "SL1001", "arena out of memory", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_UNEXPECTED_CHAR] = { "SL1002", "unexpected character", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_UNTERMINATED_STRING] = { "SL1003",
                                     "unterminated string literal",
                                     NULL,
                                     SLDiagType_ERROR,
                                     0 },
    [SLDiag_INVALID_NUMBER] = { "SL1004", "invalid number literal", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_UNEXPECTED_TOKEN] = { "SL1005", "unexpected token", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_EXPECTED_DECL] = { "SL1006", "expected declaration", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_EXPECTED_EXPR] = { "SL1007", "expected expression", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_EXPECTED_TYPE] = { "SL1008", "expected type", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_DUPLICATE_SYMBOL] = { "SL1009", "duplicate symbol", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_UNKNOWN_SYMBOL] = { "SL1010", "unknown symbol", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_UNKNOWN_TYPE] = { "SL1011", "unknown type", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_TYPE_MISMATCH] = { "SL1012", "type mismatch", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_ARITY_MISMATCH] = { "SL1013", "call arity mismatch", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_NOT_CALLABLE] = { "SL1014", "expression is not callable", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_UNKNOWN_FEATURE] = { "SL1015", "unknown feature '%s'", NULL, SLDiagType_WARNING, 1 },
    [SLDiag_RESERVED_NAME] = { "SL1016", "identifier '%s' is reserved", NULL, SLDiagType_ERROR, 1 },
    [SLDiag_RESERVED_SL_PREFIX] = { "SL1017",
                                    "identifier prefix '__sl_' is reserved",
                                    "rename symbol to avoid '__sl_' prefix",
                                    SLDiagType_ERROR,
                                    0 },
    [SLDiag_EXPECTED_BOOL] = { "SL1018", "expected bool expression", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_VOID_RETURN_TYPE] = { "SL1019",
                                  "'void' is not a valid return type",
                                  "remove 'void'",
                                  SLDiagType_ERROR,
                                  0 },
    [SLDiag_EMBEDDED_FIELD_NOT_FIRST] = { "SL1020",
                                          "embedded field must be first in struct",
                                          NULL,
                                          SLDiagType_ERROR,
                                          0 },
    [SLDiag_MULTIPLE_EMBEDDED_FIELDS] = { "SL1021",
                                          "only one embedded field is allowed",
                                          NULL,
                                          SLDiagType_ERROR,
                                          0 },
    [SLDiag_EMBEDDED_TYPE_NOT_STRUCT] = { "SL1022",
                                          "embedded field type must be a struct",
                                          NULL,
                                          SLDiagType_ERROR,
                                          0 },
    [SLDiag_EMBEDDED_CYCLE] = { "SL1023",
                                "embedded struct cycle detected",
                                NULL,
                                SLDiagType_ERROR,
                                0 },
    [SLDiag_NO_MATCHING_OVERLOAD] = { "SL1024", "no matching overload", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_AMBIGUOUS_CALL] = { "SL1025", "ambiguous call", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_INVALID_FN_GROUP_MEMBER] = { "SL1026",
                                         "invalid function-group member",
                                         NULL,
                                         SLDiagType_ERROR,
                                         0 },
    [SLDiag_DUPLICATE_FN_GROUP_MEMBER] = { "SL1027",
                                           "duplicate function-group member",
                                           NULL,
                                           SLDiagType_ERROR,
                                           0 },
    [SLDiag_INVALID_FN_GROUP_COLLISION] = { "SL1028",
                                            "function-group name collides with existing symbol",
                                            NULL,
                                            SLDiagType_ERROR,
                                            0 },
    [SLDiag_PARAM_MISSING_TYPE] = { "SL1029",
                                    "parameter '%s' is missing type",
                                    NULL,
                                    SLDiagType_ERROR,
                                    1 },
    [SLDiag_IMPORT_INVALID_PATH] = { "SL1030",
                                     "invalid import path (%s)",
                                     NULL,
                                     SLDiagType_ERROR,
                                     1 },
    [SLDiag_IMPORT_ALIAS_INFERENCE_FAILED] = { "SL1031",
                                               "cannot infer package identifier; use 'import "
                                               "\"%s\" as <name>'",
                                               NULL,
                                               SLDiagType_ERROR,
                                               1 },
    [SLDiag_IMPORT_WILDCARD_NOT_SUPPORTED] = { "SL1032",
                                               "wildcard import is not supported",
                                               NULL,
                                               SLDiagType_ERROR,
                                               0 },
    [SLDiag_IMPORT_SIDE_EFFECT_ALIAS_WITH_SYMBOLS] = { "SL1033",
                                                       "import with symbol list cannot use as _",
                                                       NULL,
                                                       SLDiagType_ERROR,
                                                       0 },
    [SLDiag_IMPORT_SYMBOL_ALIAS_INVALID] = { "SL1034",
                                             "import symbol alias '_' is not allowed",
                                             NULL,
                                             SLDiagType_ERROR,
                                             0 },
    [SLDiag_IMPORT_FEATURE_IMPORT_EXTRAS] = { "SL1035",
                                              "feature imports must be path-only (no alias or "
                                              "symbol list)",
                                              NULL,
                                              SLDiagType_ERROR,
                                              0 },
    [SLDiag_INFER_NULL_TYPE_UNKNOWN] = { "SL1036",
                                         "cannot infer type from null; add explicit type",
                                         NULL,
                                         SLDiagType_ERROR,
                                         0 },
    [SLDiag_INFER_VOID_TYPE_UNKNOWN] = { "SL1037",
                                         "cannot infer type from void expression",
                                         NULL,
                                         SLDiagType_ERROR,
                                         0 },
    [SLDiag_CONST_MISSING_INITIALIZER] = { "SL1038",
                                           "const declaration requires initializer",
                                           NULL,
                                           SLDiagType_ERROR,
                                           0 },
    [SLDiag_CONTEXT_REQUIRED] = { "SL1039", "context is required here", NULL, SLDiagType_ERROR, 0 },
    [SLDiag_CONTEXT_MISSING_FIELD] = { "SL1040",
                                       "required context field is missing",
                                       NULL,
                                       SLDiagType_ERROR,
                                       0 },
    [SLDiag_CONTEXT_TYPE_MISMATCH] = { "SL1041",
                                       "context field type mismatch",
                                       NULL,
                                       SLDiagType_ERROR,
                                       0 },
    [SLDiag_CONTEXT_UNKNOWN_FIELD] = { "SL1042",
                                       "unknown context field in with clause",
                                       NULL,
                                       SLDiagType_ERROR,
                                       0 },
    [SLDiag_CONTEXT_DUPLICATE_FIELD] = { "SL1043",
                                         "duplicate context field in with clause",
                                         NULL,
                                         SLDiagType_ERROR,
                                         0 },
    [SLDiag_CONTEXT_CLAUSE_MISMATCH] = { "SL1044",
                                         "function context clause mismatch",
                                         NULL,
                                         SLDiagType_ERROR,
                                         0 },
    [SLDiag_WITH_CONTEXT_ON_NON_CALL] = { "SL1045",
                                          "'with' context clause can only be applied to a call",
                                          NULL,
                                          SLDiagType_ERROR,
                                          0 },
    [SLDiag_COMPOUND_TYPE_REQUIRED] = { "SL1046",
                                        "compound literal requires an explicit aggregate type",
                                        NULL,
                                        SLDiagType_ERROR,
                                        0 },
    [SLDiag_COMPOUND_INFER_NO_CONTEXT] = { "SL1047",
                                           "cannot infer compound literal type from context",
                                           NULL,
                                           SLDiagType_ERROR,
                                           0 },
    [SLDiag_COMPOUND_INFER_AMBIGUOUS] = { "SL1048",
                                          "compound literal type inference is ambiguous",
                                          NULL,
                                          SLDiagType_ERROR,
                                          0 },
    [SLDiag_COMPOUND_INFER_NON_AGGREGATE] = { "SL1049",
                                              "inferred compound literal type is not an aggregate",
                                              NULL,
                                              SLDiagType_ERROR,
                                              0 },
    [SLDiag_COMPOUND_FIELD_UNKNOWN] = { "SL1050",
                                        "unknown compound literal field '%s'",
                                        NULL,
                                        SLDiagType_ERROR,
                                        1 },
    [SLDiag_COMPOUND_FIELD_DUPLICATE] = { "SL1051",
                                          "duplicate compound literal field '%s'",
                                          NULL,
                                          SLDiagType_ERROR,
                                          1 },
    [SLDiag_COMPOUND_FIELD_TYPE_MISMATCH] = { "SL1052",
                                              "compound literal field '%s' type mismatch",
                                              NULL,
                                              SLDiagType_ERROR,
                                              1 },
    [SLDiag_COMPOUND_MUT_REF_TEMPORARY] = { "SL1053",
                                            "cannot bind compound literal temporary to mutable "
                                            "reference",
                                            NULL,
                                            SLDiagType_ERROR,
                                            0 },
    [SLDiag_COMPOUND_UNION_MULTI_FIELD] = { "SL1054",
                                            "union compound literal can initialize at most one "
                                            "field",
                                            NULL,
                                            SLDiagType_ERROR,
                                            0 },
};

const char* SLDiagId(SLDiagCode code) {
    uint32_t i = (uint32_t)code;
    if (i >= (uint32_t)SLDiag__COUNT || g_slDiagInfo[i].id == NULL) {
        return "SL????";
    }
    return g_slDiagInfo[i].id;
}

const char* SLDiagMessage(SLDiagCode code) {
    uint32_t i = (uint32_t)code;
    if (i >= (uint32_t)SLDiag__COUNT || g_slDiagInfo[i].messageFmt == NULL) {
        return "unknown diagnostic";
    }
    return g_slDiagInfo[i].messageFmt;
}

const char* _Nullable SLDiagHint(SLDiagCode code) {
    uint32_t i = (uint32_t)code;
    if (i >= (uint32_t)SLDiag__COUNT) {
        return NULL;
    }
    return g_slDiagInfo[i].hint;
}

SLDiagType SLDiagTypeOfCode(SLDiagCode code) {
    uint32_t i = (uint32_t)code;
    if (i >= (uint32_t)SLDiag__COUNT) {
        return SLDiagType_ERROR;
    }
    return g_slDiagInfo[i].type;
}

uint8_t SLDiagArgCount(SLDiagCode code) {
    uint32_t i = (uint32_t)code;
    if (i >= (uint32_t)SLDiag__COUNT) {
        return 0;
    }
    return g_slDiagInfo[i].argCount;
}

SL_API_END
