name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-15

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          export PATH=$(brew --prefix llvm@18)/bin:$PATH &&
          ./build.sh test
