name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: macos-15

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          export "PATH=/opt/homebrew/opt/llvm/bin:$PATH"
          which clang || true
          which clang-format || true
          brew --prefix llvm
          ./build.sh test
